# Este archivo contiene las direcciones de la calle de la ciudad.
# Este programa contiene las clases de los agentes que se utilizan en la simulación de la ciudad.   
# Autores: 
#       A01749581 Mariana Balderrábano Aguilar	
#       A01749898 Jennyfer Nahomi Jasso Hernández	
#       A01750338 Min Che Kim				
#       A01750911 Yael Michel García López		
# Fecha de creación: 16/11/2024
# Última modificación: 17/11/2024

def getDirections():
    directions = {
        ( 2, 22): ["left", "up"],
        ( 3, 22): ["left", "up"],
        ( 4, 22): ["left", "up"],
        ( 5, 22): ["left", "up"],
        ( 6, 22): ["left", "up"],
        ( 7, 22): ["left", "up"],
        ( 8, 22): ["left", "up"],
        ( 9, 22): ["left", "up"],
        (10, 22): ["left", "up"],
        (11, 22): ["left", "up"],
        (14, 22): ["left", "up"],
        (15, 22): ["left", "up"],
        (16, 22): ["left", "up"],
        (17, 22): ["left", "up"],
        (18, 22): ["left", "up"],
        (19, 22): ["left", "up"],
        (20, 22): ["left", "up"],
        (21, 22): ["left", "up"],
        (22, 22): ["left", "up"],
        (23, 22): ["left", "up"],
        (22, 17): ["left", "up"],
        (14, 11): ["left", "up"],
        (15, 21): ["left", "up"],
        (23, 21): ["left", "up"],
        (23, 10): ["left", "up"],
        (19,  7): ["left", "up"],
        ( 4,  4): ["left", "up"],
        ( 2, 10): ["left", "up"],
        ( 3, 10): ["left", "up"],
        ( 4, 10): ["left", "up"],
        ( 5, 10): ["left", "up"],
        ( 6, 10): ["left", "up"],
        ( 7, 10): ["left", "up"],
        ( 8, 10): ["left", "up"],
        ( 9, 10): ["left", "up"],
        (10, 10): ["left", "up"],
        (11, 10): ["left", "up"],
        ( 8, 17): ["left", "up"],
        ( 9, 17): ["left", "up"],
        (10, 17): ["left", "up"],
        (11, 17): ["left", "up"],
        ( 6, 11): ["left", "up"],
        (16, 16): ["left", "up"],
        (17, 16): ["left", "up"],
        (18, 16): ["left", "up"],
        (19, 16): ["left", "up"],
        (20, 16): ["left", "up"],
        (21, 16): ["left", "up"],
        (22, 16): ["left", "up"],
        (15,  6): ["left", "up"],
        ( 7, 20): ["left", "up"],
        (15, 20): ["left", "up"],
        ( 7, 14): ["left", "up"],
        ( 3,  4): ["left", "up"],
        (16, 10): ["left", "up"],
        (17, 10): ["left", "up"],
        (18, 10): ["left", "up"],
        (19, 10): ["left", "up"],
        (20, 10): ["left", "up"],
        (21, 10): ["left", "up"],
        (19,  3): ["left", "up"],
        ( 7, 11): ["left", "up"],
        (15, 11): ["left", "up"],
        (23, 11): ["left", "up"],
        (19,  2): ["left", "up"],
        (19,  4): ["left", "up"],
        ( 7, 12): ["left", "up"],
        (15, 12): ["left", "up"],
        (23, 12): ["left", "up"],
        (23,  1): ["left", "up"],
        (19,  5): ["left", "up"],
        ( 7, 13): ["left", "up"],
        (15, 13): ["left", "up"],
        (23, 13): ["left", "up"],
        (23,  2): ["left", "up"],
        (15,  7): ["left", "up"],
        ( 7, 21): ["left", "up"],
        (23, 20): ["left", "up"],
        (23,  9): ["left", "up"],
        (15, 14): ["left", "up"],
        ( 2,  4): ["left", "up"],
        (15,  5): ["left", "up"],
        ( 7, 19): ["left", "up"],
        (15, 19): ["left", "up"],
        (23, 19): ["left", "up"],
        (23,  8): ["left", "up"],
        (15,  4): ["left", "up"],
        ( 7, 18): ["left", "up"],
        (15, 18): ["left", "up"],
        (23, 18): ["left", "up"],
        (23,  7): ["left", "up"],
        (15,  3): ["left", "up"],
        ( 7, 17): ["left", "up"],
        (15, 17): ["left", "up"],
        (23, 17): ["left", "up"],
        (23,  6): ["left", "up"],
        (15,  2): ["left", "up"],
        ( 7, 16): ["left", "up"],
        (15, 16): ["left", "up"],
        (23, 16): ["left", "up"],
        (23,  5): ["left", "up"],
        (19,  7): ["left", "up"],
        ( 7, 15): ["left", "up"],
        (15, 15): ["left", "up"],
        (23, 15): ["left", "up"],
        (23,  4): ["left", "up"],
        (23, 14): ["left", "up"],
        (23,  3): ["left", "up"],
        ( 5,  4): ["left", "up"],
        ( 1, 23): ["left", "down"],
        ( 2, 23): ["left", "down"],
        ( 3, 23): ["left", "down"],
        ( 4, 23): ["left", "down"],
        ( 5, 23): ["left", "down"],
        ( 6, 23): ["left", "down"],
        ( 7, 23): ["left", "down"],
        ( 8, 23): ["left", "down"],
        ( 9, 23): ["left", "down"],
        (10, 23): ["left", "down"],
        (11, 23): ["left", "down"],
        (12, 23): ["left", "down"],
        (13, 23): ["left", "down"],
        (14, 23): ["left", "down"],
        (15, 23): ["left", "down"],
        (16, 23): ["left", "down"],
        (17, 23): ["left", "down"],
        (18, 23): ["left", "down"],
        (19, 23): ["left", "down"],
        (20, 23): ["left", "down"],
        (21, 23): ["left", "down"],
        (22, 23): ["left", "down"],
        (16, 11): ["left", "down"],
        (17, 11): ["left", "down"],
        (18, 11): ["left", "down"],
        (19, 11): ["left", "down"],
        (20, 11): ["left", "down"],
        ( 2, 11): ["left", "down"],
        ( 3, 11): ["left", "down"],
        ( 4, 11): ["left", "down"],
        ( 5, 11): ["left", "down"],
        (12, 22): ["left", "down"],
        (12, 17): ["left", "down"],
        ( 8, 11): ["left", "down"],
        ( 9, 11): ["left", "down"],
        (10, 11): ["left", "down"],
        (11, 11): ["left", "down"],
        (12, 11): ["left", "down"],
        ( 8, 18): ["left", "down"],
        ( 9, 18): ["left", "down"],
        (10, 18): ["left", "down"],
        (11, 18): ["left", "down"],
        (12, 18): ["left", "down"],
        (16, 17): ["left", "down"],
        (17, 17): ["left", "down"],
        (18, 17): ["left", "down"],
        (19, 17): ["left", "down"],
        (20, 17): ["left", "down"],
        (21, 17): ["left", "down"],
        ( 2,  5): ["left", "down"],
        ( 3,  5): ["left", "down"],
        ( 4,  5): ["left", "down"],
        ( 5,  5): ["left", "down"],
        ( 6,  5): ["left", "down"],
        (21, 11): ["left", "down"],
        ( 1,  7): ["left", "down"],
        ( 1, 22): ["left", "down"],
        (13, 22): ["left", "down"],
        (13,  7): ["left", "down"],
        ( 1,  6): ["left", "down"],
        ( 1, 21): ["left", "down"],
        (13, 21): ["left", "down"],
        (13,  6): ["left", "down"],
        ( 1,  5): ["left", "down"],
        ( 1, 20): ["left", "down"],
        (13, 20): ["left", "down"],
        (13,  5): ["left", "down"],
        ( 1,  4): ["left", "down"],
        ( 1, 19): ["left", "down"],
        (13, 19): ["left", "down"],
        (13,  4): ["left", "down"],
        ( 1,  3): ["left", "down"],
        ( 1, 18): ["left", "down"],
        (13, 18): ["left", "down"],
        (13,  3): ["left", "down"],
        ( 1,  2): ["left", "down"],
        ( 1, 17): ["left", "down"],
        (13, 17): ["left", "down"],
        (13,  2): ["left", "down"],
        ( 7,  7): ["left", "down"],
        ( 1, 16): ["left", "down"],
        ( 7,  6): ["left", "down"],
        ( 1, 15): ["left", "down"],
        (13, 15): ["left", "down"],
        (12, 10): ["left", "down"],
        ( 6,  4): ["left", "down"],
        ( 1, 14): ["left", "down"],
        (13, 14): ["left", "down"],
        ( 1, 10): ["left", "down"],
        ( 7,  3): ["left", "down"],
        ( 1, 13): ["left", "down"],
        (13, 13): ["left", "down"],
        ( 7,  2): ["left", "down"],
        ( 1, 12): ["left", "down"],
        (13, 12): ["left", "down"],
        (13, 16): ["left", "down"],
        ( 1, 11): ["left", "down"],
        (1, 9): ["right", "down"],
        (2, 9): ["right", "down"],
        (3, 9): ["right", "down"],
        (4, 9): ["right", "down"],
        (5, 9): ["right", "down"],
        (6, 9): ["right", "down"],
        (7, 9): ["right", "down"],
        (8, 9): ["right", "down"],
        (9, 9): ["right", "down"],
        (10, 9): ["right", "down"],
        (11, 9): ["right", "down"],
        (16, 9): ["right", "down"],
        (17, 9): ["right", "down"],
        (18, 9): ["right", "down"],
        (19, 9): ["right", "down"],
        (20, 9): ["right", "down"],
        (21, 9): ["right", "down"],
        (1, 1): ["right", "down"],
        (2, 1): ["right", "down"],
        (3, 1): ["right", "down"],
        (4, 1): ["right", "down"],
        (5, 1): ["right", "down"],
        (6, 1): ["right", "down"],
        (7, 1): ["right", "down"],
        (8, 1): ["right", "down"],
        (9, 1): ["right", "down"],
        (10, 1): ["right", "down"],
        (1, 8): ["right", "down"],
        (16, 1): ["right", "down"],
        (17, 1): ["right", "down"],
        (20, 1): ["right", "down"],
        (21, 1): ["right", "down"],
        (11, 1): ["right", "down"],
        (12, 1): ["right", "down"],
        (7, 5): ["right", "down"],
        (8, 5): ["right", "down"],
        (9, 5): ["right", "down"],
        (10, 5): ["right", "down"],
        (11, 5): ["right", "down"],
        (12, 5): ["right", "down"],
        (0, 22): ["right", "down"],
        (6, 8): ["right", "down"],
        (0, 21): ["right", "down"],
        (6, 7): ["right", "down"],
        (0, 20): ["right", "down"],
        (6, 6): ["right", "down"],
        (0, 19): ["right", "down"],
        (12, 21): ["right", "down"],
        (0, 18): ["right", "down"],
        (12, 20): ["right", "down"],
        (0, 17): ["right", "down"],
        (12, 19): ["right", "down"],
        (13, 1): ["right", "down"],
        (0, 16): ["right", "down"],
        (12, 16): ["right", "down"],
        (0, 1): ["right", "down"],
        (0, 15): ["right", "down"],
        (12, 15): ["right", "down"],
        (0, 14): ["right", "down"],
        (12, 14): ["right", "down"],
        (0, 13): ["right", "down"],
        (12, 13): ["right", "down"],
        (0, 12): ["right", "down"],
        (12, 12): ["right", "down"],
        (0, 11): ["right", "down"],
        (12, 8): ["right", "down"],
        (0, 10): ["right", "down"],
        (12, 7): ["right", "down"],
        (0, 9): ["right", "down"],
        (12, 6): ["right", "down"],
        (0, 8): ["right", "down"],
        (7, 4): ["right", "down"],
        (0, 7): ["right", "down"],
        (12, 4): ["right", "down"],
        (0, 6): ["right", "down"],
        (12, 3): ["right", "down"],
        (0, 5): ["right", "down"],
        (12, 2): ["right", "down"],
        (0, 4): ["right", "down"],
        (7, 8): ["right", "down"],
        (0, 3): ["right", "down"],
        (6, 3): ["right", "down"],
        (0, 2): ["right", "down"],
        (6, 2): ["right", "down"],
        (13, 8): ["right", "down"],
        ( 1,  0): ["right", "up"],
        ( 2,  0): ["right", "up"],
        ( 3,  0): ["right", "up"],
        ( 4,  0): ["right", "up"],
        ( 5,  0): ["right", "up"],
        ( 6,  0): ["right", "up"],
        ( 7,  0): ["right", "up"],
        ( 8,  0): ["right", "up"],
        ( 9,  0): ["right", "up"],
        (10,  0): ["right", "up"],
        (11,  0): ["right", "up"],
        (12,  0): ["right", "up"],
        (13,  0): ["right", "up"],
        (14,  0): ["right", "up"],
        (15,  0): ["right", "up"],
        (16,  0): ["right", "up"],
        (17,  0): ["right", "up"],
        (18,  0): ["right", "up"],
        (19,  0): ["right", "up"],
        (20,  0): ["right", "up"],
        (21,  0): ["right", "up"],
        (22,  0): ["right", "up"],
        ( 6, 21): ["right", "up"],
        (14, 21): ["right", "up"],
        (22, 21): ["right", "up"],
        (14,  7): ["right", "up"],
        (18,  7): ["right", "up"],
        ( 8,  4): ["right", "up"],
        ( 9,  4): ["right", "up"],
        (10,  4): ["right", "up"],
        (11,  4): ["right", "up"],
        ( 2,  8): ["right", "up"],
        ( 3,  8): ["right", "up"],
        ( 4,  8): ["right", "up"],
        ( 5,  8): ["right", "up"],
        ( 8,  8): ["right", "up"],
        ( 9,  8): ["right", "up"],
        (10,  8): ["right", "up"],
        (11,  8): ["right", "up"],
        (15,  8): ["right", "up"],
        (16,  8): ["right", "up"],
        (17,  8): ["right", "up"],
        (18,  8): ["right", "up"],
        (19,  8): ["right", "up"],
        (20,  8): ["right", "up"],
        (21,  8): ["right", "up"],
        (22,  8): ["right", "up"],
        ( 6, 20): ["right", "up"],
        (14, 20): ["right", "up"],
        (22, 20): ["right", "up"],
        (14,  6): ["right", "up"],
        (18,  6): ["right", "up"],
        (22,  6): ["right", "up"],
        (22,  9): ["right", "up"],
        (22,  7): ["right", "up"],
        ( 6, 19): ["right", "up"],
        (14, 19): ["right", "up"],
        (22, 19): ["right", "up"],
        (14,  5): ["right", "up"],
        (18,  5): ["right", "up"],
        (22,  5): ["right", "up"],
        ( 6, 18): ["right", "up"],
        (14, 18): ["right", "up"],
        (22, 18): ["right", "up"],
        (14,  4): ["right", "up"],
        (18,  4): ["right", "up"],
        (22,  4): ["right", "up"],
        ( 6, 17): ["right", "up"],
        (14, 17): ["right", "up"],
        (22, 15): ["right", "up"],
        (14,  3): ["right", "up"],
        (18,  3): ["right", "up"],
        (22,  3): ["right", "up"],
        ( 6, 16): ["right", "up"],
        (14, 16): ["right", "up"],
        (22, 14): ["right", "up"],
        (14,  2): ["right", "up"],
        (18,  2): ["right", "up"],
        (22,  2): ["right", "up"],
        (14, 12): ["right", "up"],
        (22, 10): ["right", "up"],
        ( 6, 15): ["right", "up"],
        (14, 15): ["right", "up"],
        (22, 13): ["right", "up"],
        (14,  1): ["right", "up"],
        (18,  1): ["right", "up"],
        (22,  1): ["right", "up"],
        ( 6, 14): ["right", "up"],
        (14, 14): ["right", "up"],
        (22, 12): ["right", "up"],
        (15,  9): ["right", "up"],
        (15,  1): ["right", "up"],
        (19,  1): ["right", "up"],
        ( 6, 13): ["right", "up"],
        (14, 13): ["right", "up"],
        (22, 11): ["right", "up"],
        ( 6, 12): ["right", "up"],
        (13, 11): ["left"],
        (23, 23): ["left"],
        ( 0,  0): ["right"],
        (14,  8): ["right"],
        (23,  0): ["up"],
        (15, 10): ["up"],
        ( 0, 23): ["down"],
        (12,  9): ["down"]
    }
    return directions